version: "3"

services:
  app:
    image: webdevops/php-apache-dev:7.3
    ports: 
      - "${BACKEND_SERVER_PORT}:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes: 
      - ../app:/app
  db:
    image: postgres:11
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - "${DB_PORT}:5432"